//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paintr.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43, 43, 43")]
        public global::System.Drawing.Color BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColor"]));
            }
            set {
                this["BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TextColor {
            get {
                return ((global::System.Drawing.Color)(this["TextColor"]));
            }
            set {
                this["TextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60, 60, 60")]
        public global::System.Drawing.Color ButtonBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonBackgroundColor"]));
            }
            set {
                this["ButtonBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("190, 190, 190")]
        public global::System.Drawing.Color TextUnsavedColor {
            get {
                return ((global::System.Drawing.Color)(this["TextUnsavedColor"]));
            }
            set {
                this["TextUnsavedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50, 50")]
        public global::System.Drawing.Color TextDisabledColor {
            get {
                return ((global::System.Drawing.Color)(this["TextDisabledColor"]));
            }
            set {
                this["TextDisabledColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100, 100")]
        public global::System.Drawing.Color ButtonBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonBorderColor"]));
            }
            set {
                this["ButtonBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110, 110, 110")]
        public global::System.Drawing.Color ButtonMouseOverColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonMouseOverColor"]));
            }
            set {
                this["ButtonMouseOverColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120, 120, 120")]
        public global::System.Drawing.Color ButtonMouseDownColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonMouseDownColor"]));
            }
            set {
                this["ButtonMouseDownColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color WindowGripColor {
            get {
                return ((global::System.Drawing.Color)(this["WindowGripColor"]));
            }
            set {
                this["WindowGripColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 126, 200")]
        public global::System.Drawing.Color ContrastBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["ContrastBackgroundColor"]));
            }
            set {
                this["ContrastBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 100, 175")]
        public global::System.Drawing.Color ContrastBackgroundDownColor {
            get {
                return ((global::System.Drawing.Color)(this["ContrastBackgroundDownColor"]));
            }
            set {
                this["ContrastBackgroundDownColor"] = value;
            }
        }
    }
}
