//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paintr.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paintr.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Picker.
        /// </summary>
        internal static string BrushColorPicker {
            get {
                return ResourceManager.GetString("BrushColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Bucket.
        /// </summary>
        internal static string BrushFill {
            get {
                return ResourceManager.GetString("BrushFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ink Pen.
        /// </summary>
        internal static string BrushInkPen {
            get {
                return ResourceManager.GetString("BrushInkPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Brush.
        /// </summary>
        internal static string BrushPaintBrush {
            get {
                return ResourceManager.GetString("BrushPaintBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Perfect.
        /// </summary>
        internal static string BrushPixelPerfect {
            get {
                return ResourceManager.GetString("BrushPixelPerfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rect Select.
        /// </summary>
        internal static string BrushRectSelect {
            get {
                return ResourceManager.GetString("BrushRectSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Brush.
        /// </summary>
        internal static string BrushSelectBrush {
            get {
                return ResourceManager.GetString("BrushSelectBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string BrushText {
            get {
                return ResourceManager.GetString("BrushText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ButtonConfirm {
            get {
                return ResourceManager.GetString("ButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string ButtonOkay {
            get {
                return ResourceManager.GetString("ButtonOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image is on the clipboard..
        /// </summary>
        internal static string ClipboardNoImage {
            get {
                return ResourceManager.GetString("ClipboardNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer {0}.
        /// </summary>
        internal static string DefaultLayerName {
            get {
                return ResourceManager.GetString("DefaultLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        internal static string GenericLayerName {
            get {
                return ResourceManager.GetString("GenericLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Grayscale Selection.
        /// </summary>
        internal static string GrayscaleSelectionMenu {
            get {
                return ResourceManager.GetString("GrayscaleSelectionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend Mode.
        /// </summary>
        internal static string LabelLayerBlendMode {
            get {
                return ResourceManager.GetString("LabelLayerBlendMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LabelLayerName {
            get {
                return ResourceManager.GetString("LabelLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string LabelLayerOpacity {
            get {
                return ResourceManager.GetString("LabelLayerOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        internal static string LayersLabel {
            get {
                return ResourceManager.GetString("LayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Image....
        /// </summary>
        internal static string MenuOpenImage {
            get {
                return ResourceManager.GetString("MenuOpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        internal static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Negate Selection.
        /// </summary>
        internal static string NegateSelectionMenu {
            get {
                return ResourceManager.GetString("NegateSelectionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Fail.
        /// </summary>
        internal static string PasteFail {
            get {
                return ResourceManager.GetString("PasteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel &amp;Grid.
        /// </summary>
        internal static string PixelGridMenu {
            get {
                return ResourceManager.GetString("PixelGridMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Protractor.
        /// </summary>
        internal static string ProtractorMenu {
            get {
                return ResourceManager.GetString("ProtractorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset &amp;View.
        /// </summary>
        internal static string ResetViewMenu {
            get {
                return ResourceManager.GetString("ResetViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ruler.
        /// </summary>
        internal static string RulerMenu {
            get {
                return ResourceManager.GetString("RulerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicubic.
        /// </summary>
        internal static string ScalingBicubic {
            get {
                return ResourceManager.GetString("ScalingBicubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinear.
        /// </summary>
        internal static string ScalingBilinear {
            get {
                return ResourceManager.GetString("ScalingBilinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Neighbor.
        /// </summary>
        internal static string ScalingNearestNeighbor {
            get {
                return ResourceManager.GetString("ScalingNearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelPos: {0}, {1}; SelSize: {2}, {3}.
        /// </summary>
        internal static string SelectionStatusLabel {
            get {
                return ResourceManager.GetString("SelectionStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighten.
        /// </summary>
        internal static string ShaderLighten {
            get {
                return ResourceManager.GetString("ShaderLighten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string ShaderStandard {
            get {
                return ResourceManager.GetString("ShaderStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tile View.
        /// </summary>
        internal static string TileModeMenu {
            get {
                return ResourceManager.GetString("TileModeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom: {0}; Position: {1}, {2}.
        /// </summary>
        internal static string ViewportStatusLabel {
            get {
                return ResourceManager.GetString("ViewportStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Brush.
        /// </summary>
        internal static string WindowTitleSelectBrush {
            get {
                return ResourceManager.GetString("WindowTitleSelectBrush", resourceCulture);
            }
        }
    }
}
